### ISSUE TITLE
Submodule for each code (civil, pénal, etc.)

### ISSUE THREAD

**Issue by EHadoux** [steeve/france.code-civil#30]
It would be interesting and more _broad audience_ to have one repository including, as submodules, all the others. I guess it could be a pain for non-tech people to either know all the links or struggle to find them on GitHub.
On the opposite, it would be more efficient for public announcement to have one known link.
What do you think?

**Comment by LeoColomb** [comment]
> have one repository

Une organisation GitHub serai bien plus cohérente ! :smile:

**Comment by EHadoux** [comment]
Cohérente, pas forcément, pratique, probablement.

**Comment by steeve** [comment]
I am currently scraping all the Codes on legifrance, and plan to do a repo with all the codes in it. I feel it's more coherent since some laws have changes that span multiple codes

I am also re-writing the markdown formatter from Python to Go as it is too slow to handle all the codes by itself (300mb worth of JSON).

**Comment by thibaultmeyer** [comment]
:+1:  @LeoColomb . On pourrait imaginer une organisation "Droit Français" avec un repository par "type" (ex: Constitution, Droit du travail, Code Civil, ...) et derriere pk pas un site statis en droit-francais.github.io pour présenter le tout.

**Comment by Akryum** [comment]
J'ai commencé un prototype de site statique pour présenter le contenu du repo et les commits.

**Comment by EHadoux** [comment]
Tu veux dire les différentes évolution d'une loi via les commits ? Parce que master est dans le GitBook.
